import asyncio
import logging
from datetime import date, datetime, timezone
from pathlib import Path
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from typer import Argument, Typer
from app.config.db import engine
from app.models.users import User, UserRole


app = Typer()
ALEMBIC_INI = Path(__file__).resolve().parent / 'alembic.ini'
logger = logging.getLogger(__name__)

def _alembic_config() -> Config:
    return Config(str(ALEMBIC_INI))


async def _new_user(email: str, password: str, role: UserRole):
    async with AsyncSession(engine) as session:
        try:
            result = await session.execute(select(User).where(User.email == email))
            if result.scalar_one_or_none() is not None:
                logger.warning(f"User with email '{email}' already exists.")
                return
            unix = date(1970, 1, 1)
            session.add(User(email=email, password=password, role=role, birthdate=unix))
            await session.flush()
            await session.commit()
        except Exception as e:
            logger.exception(e)
            await session.rollback()


@app.command('createuser')
def create_user(email: str, password: str):
    return asyncio.run(_new_user(email, password, UserRole.Reader))


@app.command('createsuperuser')
def create_superuser(email: str, password: str):
    return asyncio.run(_new_user(email, password, UserRole.Admin))


@app.command('makemigrations')
def make_migrations(message: str = Argument(None, help='Short description of the migration')):
    config = _alembic_config()
    script = ScriptDirectory.from_config(config)
    head = script.get_current_head()
    if message is None:
        msg_last = '' if head is None else f" from migration #{head}"
        message = f"[autogenerated] Migration covers all changes{msg_last} until {datetime.now(timezone.utc).strftime('%Y-%b-%d %I:%M:%S%p (%Z)').upper()}"
    command.revision(config, message=message, autogenerate=True)


@app.command('migrate')
def migrate(revision: str = Argument('head', help='Target revision to migrate to')):
    command.upgrade(_alembic_config(), revision)


if __name__ == '__main__':
    app()