"""[autogenerated] Migration covers all changes until 2026-SEP-09 08:17:24PM (UTC)

Revision ID: 9b4c366982fd
Revises: 
Create Date: 2026-09-09 15:17:24.982594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b4c366982fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('Vertical', 'Horizontal', name='readingdirection').create(op.get_bind())
    sa.Enum('Draft', 'Preview', 'Ongoing', 'OnHiatus', 'Completed', 'Canceled', name='completionstatus').create(op.get_bind())
    sa.Enum('LTR', 'RTL', 'TTB', name='horizontalcontent').create(op.get_bind())
    sa.Enum('Light', 'Dark', 'System', name='appthemes').create(op.get_bind())
    sa.Enum('Spanish', 'English', 'Chinese', 'Japanese', 'Korean', name='supportedlanguages').create(op.get_bind())
    sa.Enum('Male', 'Female', 'Other', 'RatherNotSay', name='usergenders').create(op.get_bind())
    sa.Enum('Reader', 'Creator', 'Staff', 'Admin', name='userroles').create(op.get_bind())
    op.create_table('series_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_tags_tag_name'), 'series_tags', ['tag_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', postgresql.ENUM('Reader', 'Creator', 'Staff', 'Admin', name='userroles', create_type=False), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('otp', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('Draft', 'Preview', 'Ongoing', 'OnHiatus', 'Completed', 'Canceled', name='completionstatus', create_type=False), nullable=False),
    sa.Column('thumbnail_key', sa.String(), nullable=True),
    sa.Column('banner_key', sa.String(), nullable=True),
    sa.Column('reading_direction', postgresql.ENUM('Vertical', 'Horizontal', name='readingdirection', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_title'), 'series', ['title'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('profile_picture_key', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('gender', postgresql.ENUM('Male', 'Female', 'Other', 'RatherNotSay', name='usergenders', create_type=False), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_display_name'), 'user_profiles', ['display_name'], unique=True)
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_language', postgresql.ENUM('Spanish', 'English', 'Chinese', 'Japanese', 'Korean', name='supportedlanguages', create_type=False), nullable=False),
    sa.Column('ui_language', postgresql.ENUM('Spanish', 'English', 'Chinese', 'Japanese', 'Korean', name='supportedlanguages', create_type=False), nullable=False),
    sa.Column('theme', postgresql.ENUM('Light', 'Dark', 'System', name='appthemes', create_type=False), nullable=False),
    sa.Column('horizontal_content_navigation', postgresql.ENUM('LTR', 'RTL', 'TTB', name='horizontalcontent', create_type=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series_collections',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('thumbnail_key', sa.String(), nullable=True),
    sa.Column('banner_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_collections_index'), 'series_collections', ['index'], unique=False)
    op.create_table('series_tag_associations',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['series_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'tag_id')
    )
    op.create_table('user_social_handles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uniq_url_per_platform', 'user_social_handles', ['platform', 'url'], unique=True)
    op.create_table('series_episodes',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('thumbnail_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['series_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_episodes_index'), 'series_episodes', ['index'], unique=False)
    op.create_table('episode_reader_media',
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['series_episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_reader_media_index'), 'episode_reader_media', ['index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_reader_media_index'), table_name='episode_reader_media')
    op.drop_table('episode_reader_media')
    op.drop_index(op.f('ix_series_episodes_index'), table_name='series_episodes')
    op.drop_table('series_episodes')
    op.drop_index('uniq_url_per_platform', table_name='user_social_handles')
    op.drop_table('user_social_handles')
    op.drop_table('series_tag_associations')
    op.drop_index(op.f('ix_series_collections_index'), table_name='series_collections')
    op.drop_table('series_collections')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_profiles_display_name'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_series_title'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_series_tags_tag_name'), table_name='series_tags')
    op.drop_table('series_tags')
    sa.Enum('Reader', 'Creator', 'Staff', 'Admin', name='userroles').drop(op.get_bind())
    sa.Enum('Male', 'Female', 'Other', 'RatherNotSay', name='usergenders').drop(op.get_bind())
    sa.Enum('Spanish', 'English', 'Chinese', 'Japanese', 'Korean', name='supportedlanguages').drop(op.get_bind())
    sa.Enum('Light', 'Dark', 'System', name='appthemes').drop(op.get_bind())
    sa.Enum('LTR', 'RTL', 'TTB', name='horizontalcontent').drop(op.get_bind())
    sa.Enum('Draft', 'Preview', 'Ongoing', 'OnHiatus', 'Completed', 'Canceled', name='completionstatus').drop(op.get_bind())
    sa.Enum('Vertical', 'Horizontal', name='readingdirection').drop(op.get_bind())
    # ### end Alembic commands ###
